PROJECT="LiveChat"
CLUSTER_NAME="LiveChatEKSCluster"
USERNAME="Hemmo"
REGION="eu-north-1"

EKS_KUBERNETES_VERSION="1.31"
METRICS_SERVER_VERSION="v0.7.2"
EKS_INSTANCE_TYPE="t3.medium"
EKS_DESIRED_NODES=2
EKS_MIN_NODES=1
EKS_MAX_NODES=3

NUM_REDIS_REPLICAS=1

BACKEND_MIN_REPLICAS=2
BACKEND_MAX_REPLICAS=4
BACKEND_TARGET_CPU_UTILIZATION_PCT=80

UI_MIN_REPLICAS=2
UI_MAX_REPLICAS=4
UI_TARGET_CPU_UTILIZATION_PCT=80

BACKEND_MEMORY_REQUEST="200Mi"
BACKEND_MEMORY_LIMIT="500Mi"
BACKEND_CPU_REQUEST="100m"
BACKEND_CPU_LIMIT="500m"

UI_MEMORY_REQUEST="200Mi"
UI_MEMORY_LIMIT="500Mi"
UI_CPU_REQUEST="100m"
UI_CPU_LIMIT="500m"

BACKEND_MODULE_PORT=5000
UI_MODULE_PORT=8000
REDIS_PORT=6379