project:
  name: "LiveChat"
  cluster_name: "LiveChatEKSCluster"
  username: "Hemmo"
  region: "eu-north-1"

helm:
  aws_load_balancer_controller_chart_version: "1.10.0"

eks:
  kubernetes_version: "1.31"
  metrics_server_version: "v0.7.2"
  instance_type: "t3.medium"
  desired_nodes: 3
  min_nodes: 2
  max_nodes: 4

backend_module:
  min_replicas: 2
  max_replicas: 4
  target_cpu_utilization_pct: 80
  memory_request: "200Mi"
  memory_limit: "500Mi"
  cpu_request: "100m"
  cpu_limit: "500m"
  module_port: 5000

ui_module:
  min_replicas: 2
  max_replicas: 4
  target_cpu_utilization_pct: 80
  memory_request: "200Mi"
  memory_limit: "500Mi"
  cpu_request: "100m"
  cpu_limit: "500m"
  module_port: 8000

redis:
  version: "7.4.1"
  num_master_replicas: 3
  num_slaves_per_master: 1
  storage_size: "1Gi"
  port: 6379
  cluster_bus_port: 16379

rabbitmq:
  version: "3.9"
  num_replicas: 3
  port: 5672
  discovery_port: 4369
