apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  secret_key: {{ .Values.flaskSecretKey }}
