apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  RABBIT_USERNAME: "{{ .Values.rabbitUsername | b64enc }}"
  RABBIT_PASSWORD: "{{ .Values.rabbitPassword | b64enc }}"
