apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-broker-deployment
  labels:
    app: redis-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-broker
  template:
    metadata:
      labels:
        app: redis-broker
    spec:
      containers:
        - name: redis-broker
          image: redis:latest
          ports:
            - containerPort: {{ .Values.redisPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-broker-service
  labels:
    app: redis-broker
spec:
  type: ClusterIP
  selector:
    app: redis-broker
  ports:
    - protocol: TCP
      port: {{ .Values.redisPort }}
      targetPort: {{ .Values.redisPort }}
