apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  REDIS_PASSWORD: "{{ .Values.redisPassword | b64enc }}"
