apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-serviceaccount
  namespace: kube-system
  labels:
    app.kubernetes.io/name: ebs-csi-controller-serviceaccount
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.ebsCsiDriverRoleArn }}"
