apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-messagebroker
  labels:
    app: redis-messagebroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-messagebroker
  template:
    metadata:
      labels:
        app: redis-messagebroker
    spec:
      containers:
        - name: redis-messagebroker
          image: "redis:{{ .Values.redisVersion }}"
          ports:
            - containerPort: {{ .Values.redisPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redisPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-messagebroker-service
  labels:
    app: redis-messagebroker
spec:
  type: ClusterIP
  selector:
    app: redis-messagebroker
  ports:
    - protocol: TCP
      port: {{ .Values.redisPort }}
      targetPort: {{ .Values.redisPort }}
