version: "3"
services:
  frontend_service:
    build: ./frontend
    ports:
      - "5001:5001"
    volumes:
      - ./frontend:/app

  backend_service:
    build: ./backend
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend_service
      - backend_service
