version: "3"
services:
  
  frontend_service:
    build: ./frontend
    ports:
      - "8000"

  backend_service1:
    build: ./backend
    ports:
      - "5000"
    depends_on:
      - redis

  backend_service2:
    build: ./backend
    ports:
      - "5000"
    depends_on:
      - redis

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"
    depends_on:
      - frontend_service
      - backend_service1
      - backend_service2

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
