version: "3"
services:
  
  ui_service:
    build: ./ui
    ports:
      - "8000"  # ports directive can be removed to prevent access from local machine
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "false"
      FLASK_SECRET_KEY: your_secret_key
      BACKEND_URL: http://nginx/api

  backend_service:
    build: ./backend
    ports:
      - "5000"  # ports directive can be removed to prevent access from local machine
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "false"
      FLASK_SECRET_KEY: your_secret_key
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NGINX_HOST: localhost
      NGINX_PORT: 9999
    deploy:
      replicas: 2
    depends_on:
      - redis

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"  # access localhost:9999 to route traffic with nginx
    depends_on:
      - ui_service
      - backend_service

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
